name: SuperCalculator CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    - name: Building
      run: dotnet build --configuration Release

    - name: Running Unit Tests
      run: dotnet test

    - name: Getting the Release Version
      id: get_release_version
      if: github.event_name == 'release'
      run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

    - name: Echoing the Version
      if: github.event_name == 'release'
      run: echo ${{ steps.get_release_version.outputs.tag }}
